title: Yilun's Doc
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://yilunkuang.github.io/Yilun_Doc

aux_links: 
  Template Repository: https://github.com/YilunKuang/Yilun_Doc

math: mathjax

# Add custom CSS
assets:
  css:
    - "assets/css/color.css"
